### ISSUE TITLE
Can't access student dashboard!

### ISSUE THREAD

**Issue by aurora-07** [iamrohitsuthar/Quizller#15]
can you confirm the URL by which you access the student login. 
i do it by : localhost/Quizller/files/student_login.php 
                 localhost/Quizller/index.php
they both give the same page of student login but when i put the correct username and password it neither shows any message and it reloads the page.
![image](https://user-images.githubusercontent.com/61545771/84146571-54debb00-aa75-11ea-8baf-30c7d36f9c92.png)
 
can't enter a student to class
![image](https://user-images.githubusercontent.com/61545771/84146672-7d66b500-aa75-11ea-9660-7fe08da13838.png)

**Comment by iamrohitsuthar** [comment]
You can access student login panel through index.php

If you logged in into the dashboard and then after logout, you cannot log in again. Because one student should not be able to give the test again by the same test credentials.

Adding external students try to enter userid in string format. Currently, it only allows username I will add userid option in numeric format.

Let me know if you face any other issues.

**Comment by aurora-07** [comment]
I login to the student panel through 
localhost/Quizller/index.php which shows me this.
![image](https://user-images.githubusercontent.com/61545771/84147549-05998a00-aa77-11ea-8334-c01f22bc6fd0.png)
Further I add the student credentials from the dummy data you provided and after pressing the login button this page shows up again.
![image](https://user-images.githubusercontent.com/61545771/84147597-1e09a480-aa77-11ea-8c7b-bc6fa3ea572b.png)

**Comment by aurora-07** [comment]
![image](https://user-images.githubusercontent.com/61545771/84148164-fff07400-aa77-11ea-8b9b-74a0e586b9e3.png)

Not accepting in the string format either.

**Comment by aurora-07** [comment]
Still can't access it.
